// Importing Navbar and Footer components
import {Navbar, Footer} from '@/components/index'
import ThemeContext from '@/context/ThemeContext'
import './globals.css'
import { Inter } from 'next/font/google'





const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SpeedyCarRentals',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContext>
        <Navbar/>
        {children}
        <Footer/>
        </ThemeContext>
        
        
        </body>
    </html>
  )
}
